apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: smarthome
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.11.0
    chart: grafana
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts: 
          - grafana.k8s.lan
          - grafana.rock.k8s.vogelherdweg.de
          - grafana.internal.k8s.vogelherdweg.de
          tls: 
          - hosts: 
            - grafana.rock.k8s.vogelherdweg.de
            - grafana.internal.k8s.vogelherdweg.de
            secretName: grafana-rock-k8s-vogelherdweg-de-tls
        admin:
          existingSecret: grafana-secret
        datasources:
          datatasources.yaml:
            apiVersion: 1
            datasources:
            - name: InfluxDB
              type: influxdb 
              url: "https://influx.rock.k8s.vogelherdweg.de"
              jsonData:
                version: Flux
                organization: "influxdata"
                defaultBucket: default
              secureJsonData: 
                token: "$INFLUX_TOKEN"
            - name: Prometheus
              type: prometheus
              url: 'https://prometheus.internal.k8s.vogelherdweg.de'
        envValueFrom:
          INFLUX_TOKEN:
            secretKeyRef:
              name: influxdb-secret
              key: admin-token
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-client-secret
              key: client-secret
        env:
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            environment:
              url: https://gist.githubusercontent.com/MyChaOS87/6e0fcaf0cf929e3a6add87f5b22a8b53/raw/b6618cfadc10f93f3bd38329c87025fb724d031d/Environment.json
            power:
              url: https://gist.githubusercontent.com/MyChaOS87/6e0fcaf0cf929e3a6add87f5b22a8b53/raw/b6618cfadc10f93f3bd38329c87025fb724d031d/Power.json
            prometheus-stats:
              gnetId: 15489
              datasource: Prometheus
            version-checker:
              gnetId: 12833
              datasource: Prometheus
            kubernetes-cluster:
              gnetId: 15282
              datasource: Prometheus
            influxdb-stats:
              gnetId: 421
              datasource: InfluxDB
        grafana.ini:
          server:
            domain: grafana.internal.k8s.vogelherdweg.de
            root_url: https://grafana.internal.k8s.vogelherdweg.de
          auth.generic_oauth:
            enabled: true
            name: Keycloak
            allow_sign_up: true
            client_id: grafana
            scopes: openid email profile offline_access roles
            email_attribute_path: email
            login_attribute_path: username
            name_attribute_path: full_name
            auth_url: https://sso.internal.k8s.vogelherdweg.de/realms/vogelherdweg/protocol/openid-connect/auth
            token_url: https://sso.internal.k8s.vogelherdweg.de/realms/vogelherdweg/protocol/openid-connect/token
            api_url: https://sso.internal.k8s.vogelherdweg.de/realms/vogelherdweg/protocol/openid-connect/userinfo
            role_attribute_path: contains(resource_access.grafana.roles[*], 'admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || 'Viewer'
            role_attribute_strict: true
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: deployments/smarthome/grafana-secrets
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: deployments/smarthome/influxdb-secrets
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true