apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  destination:
    namespace: telegraf
    server: https://kubernetes.default.svc
  project: smarthome
  sources:
  - repoURL: https://helm.influxdata.com/
    targetRevision: 1.8.50
    chart: telegraf
    helm:
      parameters:
        - name: tplVersion
          value: "2"
      values: |
        service:
          enabled: false
        config:
          agent:
            debug: true
          processors:
          outputs:
            - influxdb_v2:
                urls:
                  - "https://influx.rock.k8s.vogelherdweg.de"
                token: "${INFLUX_TOKEN}"
                organization: "influxdata"
                bucket: "default"
                insecure_skip_verify: true
          inputs:
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.rock.k8s.vogelherdweg.de:1883"
                topics: 
                  - "shellies/+/+/+/power"
                  - "shellies/+/+/+/energy"
                  - "shellies/+/+/+/voltage"
                  - "shellies/+/+/+/current"
                  - "shellies/+/sensor/temperature"
                  - "shellies/+/sensor/humidity"
                  - "shellies/+/sensor/battery"
                data_format: "value"
                data_type: "float"
                topic_parsing:
                  - topic: "shellies/+/+/+/+"
                    measurement: "_/_/_/_/measurement"
                    tags: "_/shelly_id/shelly_type/sub_id/_"
                  - topic: "shellies/+/sensor/+"
                    measurement: "_/_/_/measurement"
                    tags: "_/shelly_id/shelly_type/_"
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.rock.k8s.vogelherdweg.de:1883"
                topics: 
                  - "warp2/22hg/meter/values"
                data_format: "json_v2"
                topic_parsing:
                  - topic: "warp2/22hg/meter/values"
                    tags: "_/wallbox_name/_/_"
                json_v2:
                  - measurement_name: "power"
                    field:
                      - path: "power"
                        type: "float"
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.rock.k8s.vogelherdweg.de:1883"
                topics: 
                  - "shellies_plus/+/status/temperature:0"
                data_format: "json_v2"
                topic_parsing:
                  - topic: "shellies_plus/+/status/+"
                    tags: "_/shelly_id/_/_"
                json_v2:
                  - measurement_name: "temperature"
                    field:
                      - path: "tC"
                        rename: "temperature"
                        type: "float"
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.rock.k8s.vogelherdweg.de:1883"
                topics: 
                  - "shellies_plus/+/status/humidity:0"
                data_format: "json_v2"
                topic_parsing:
                  - topic: "shellies_plus/+/status/+"
                    tags: "_/shelly_id/_/_"
                json_v2:
                  - measurement_name: "humidity"
                    field:
                      - path: "rh"
                        rename: "humidity"
                        type: "float"
            - mqtt_consumer:
                servers:
                  - "tcp://mosquitto.rock.k8s.vogelherdweg.de:1883"
                topics: 
                  - "shellies_pro/+/status/em:0"
                data_format: "json_v2"
                topic_parsing:
                  - topic: "shellies_pro/+/status/+"
                    tags: "_/shelly_id/_/_"
                json_v2:
                  - measurement_name: "em:0"
                    field:
                      - path: "a_current"
                        type: "float"
                      - path: "a_voltage"
                        type: "float"
                      - path: "a_act_power"
                        type: "float"
                      - path: "a_aprt_power"
                        type: "float"
                      - path: "a_pf"
                        type: "float"
                      - path: "a_freq"
                        type: "float"
                      - path: "b_current"
                        type: "float"
                      - path: "b_voltage"
                        type: "float"
                      - path: "b_act_power"
                        type: "float"
                      - path: "b_aprt_power"
                        type: "float"
                      - path: "b_pf"
                        type: "float"
                      - path: "b_freq"
                        type: "float"
                      - path: "c_current"
                        type: "float"
                      - path: "c_voltage"
                        type: "float"
                      - path: "c_act_power"
                        type: "float"
                      - path: "c_aprt_power"
                        type: "float"
                      - path: "c_pf"
                        type: "float"
                      - path: "c_freq"
                        type: "float"
                      - path: "n_current"
                        type: "float"
                      - path: "total_current"
                        type: "float"
                      - path: "total_act_power"
                        type: "float"
                      - path: "total_aprt_power"
                        type: "float"
            - modbus:
                name: "pluggit_modbus"
                slave_id: 1
                timeout: "1s"
                controller: "tcp://192.168.1.19:502"
                configuration_type: "register"
                holding_registers: 
                - name: "CurrentBLState"
                  byte_order: "CDAB"
                  data_type: "UINT32"
                  scale: !!float 1.0000001
                  address: 
                    - 472
                    - 473
                - name: "RamIdxT1"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 132
                    - 133
                - name: "RamIdxT2"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 134
                    - 135 
                - name: "RamIdxT3"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 136
                    - 137
                - name: "RamIdxT4"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 138
                    - 139
                - name: "RomIdxSpeedLevel"
                  byte_order: "CDAB"
                  data_type: "UINT32"
                  scale: !!float 1.0000001
                  address: 
                    - 324
                    - 325
                - name: "HALTaho1"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 100
                    - 101
                - name: "HALTaho2"
                  byte_order: "CDAB"
                  data_type: "FLOAT32-IEEE"
                  scale: !!float 1.0000001
                  address: 
                    - 102
                    - 103
                - name: "RamIdxBypassActualState"
                  byte_order: "CDAB"
                  data_type: "UINT32"
                  scale: !!float 1.0000001
                  address: 
                    - 198
                    - 199
                - name: "VOC"
                  byte_order: "CDAB"
                  data_type: "UINT32"
                  scale: !!float 1.0000001
                  address: 
                    - 430
                    - 431        
        env:        
          - name: INFLUX_TOKEN
            valueFrom: 
              secretKeyRef:
                name: influxdb-secret
                key: admin-token
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: deployments/smarthome/influxdb-secrets
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true