{
 "title": "Vogelherdweg 2A - Environment",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"regexp\"\nfrom(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> filter(fn: (r) => not exists r.shelly_type or r.shelly_type != \"relay\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with shelly_id: regexp.replaceAllString(r: /^shelly(plugs|plugm|plug|plusht|htblue|ht)-/, v: r.shelly_id, t: \"\") }))\n  |> drop(columns: [\"host\"])\n"
    }
   ]
  },
  {
   "title": "Last Temperatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\nfrom(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> filter(fn: (r) => not exists r.shelly_type or r.shelly_type != \"relay\")\n  |> last()\n  |> map(fn: (r) => ({ r with shelly_id: regexp.replaceAllString(r: /^shelly(plugs|plugm|plug|plusht|htblue|ht)-/, v: r.shelly_id, t: \"\") }))\n  |> drop(columns: [\"host\"])\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"regexp\"\nfrom(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with shelly_id: regexp.replaceAllString(r: /^shelly(plugs|plugm|plug|plusht|htblue|ht)-/, v: r.shelly_id, t: \"\") }))\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "import \"regexp\"\nfrom(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_value\"] < 90)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with shelly_id: regexp.replaceAllString(r: /^shelly(plugs|plugm|plug|plusht|htblue|ht)-/, v: r.shelly_id, t: \"\") }))\n  |> drop(columns: [\"host\"])"
    }
   ]
  }
 ]
}