{
 "title": "Vogelherdweg 2a - Power",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall Consumption Stacked",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"em:0\" and r._field =~ /^[a-c]_act_power$/)\n  |> map(fn: (r) => ({r with sub_id: if r._field == \"a_act_power\" then \"0\" else if r._field == \"b_act_power\" then \"1\" else \"2\"}))\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Wallbox",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r.wallbox_name == \"22hg\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Consumption in timeframe ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"em:0\" and r._field =~ /^[a-c]_act_power$/)\n  |> map(fn: (r) => ({r with sub_id: if r._field == \"a_act_power\" then \"0\" else if r._field == \"b_act_power\" then \"1\" else \"2\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"host\"])\n  |> integral(unit: 1h, interpolate: \"\")"
    }
   ]
  },
  {
   "title": "Overall Consumption",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"em:0\" and r._field =~ /^[a-c]_act_power$/)\n  |> map(fn: (r) => ({r with sub_id: if r._field == \"a_act_power\" then \"0\" else if r._field == \"b_act_power\" then \"1\" else \"2\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Outlets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r.shelly_type == \"relay\" and\n    r._value < 5000\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r.shelly_type == \"relay\" and\n    r._value < 5000\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"host\"])\n  |> integral(unit: 1h, interpolate: \"\")"
    }
   ]
  }
 ]
}