apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.13.3
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: cluster-essentials/cert-manager-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true