apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.7.8
    chart: external-dns
    helm:
      values: |
        provider: google
        google:
          project: "vogelherd"          
          serviceAccountSecret: "gcloud-external-dns"
          serviceAccountSecretKey: "gcloud-external-dns.key.json"
        # domainFilters:
        # - rock.k8s.vogelherdweg.de
        podAnnotations:
          use-metadata.version-checker.io/external-dns: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: cluster-essentials/external-dns-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true