apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      values: |       
        sources:
          - service
          - ingress

        provider:
          name: google

        extraArgs:
          - --google-project=vogelherd
          # - --domain-filter=rock.k8s.vogelherdweg.de
        
        extraVolumeMounts:
          - name: gcloud-sa
            mountPath: /etc/kubernetes/
            readOnly: true
        
        extraVolumes:
          - name: gcloud-sa
            secret:
              secretName: gcloud-external-dns 
              items:
                - key: gcloud-external-dns.key.json
                  path: gcloud-key.json 
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/kubernetes/gcloud-key.json

        podAnnotations:
          use-metadata.version-checker.io/external-dns: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: cluster-essentials/external-dns-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true