apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.2
    chart: sealed-secrets
    helm: 
      values: |
        fullnameOverride: sealed-secrets-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: cluster-essentials
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
