apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-checker
  namespace: argocd
spec:
  destination:
    namespace: version-checker
    server: https://kubernetes.default.svc
  project: cluster-essentials
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 0.8.6
    chart: version-checker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
