apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.15
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        configs:
          params: 
            server.insecure: true
          cm:
            url: https://argocd.internal.k8s.vogelherdweg.de
            oidc.config: |
              name: Keycloak
              issuer: https://sso.internal.k8s.vogelherdweg.de/realms/vogelherdweg
              clientID: argocd
              clientSecret: $argocd-client-secret:client-secret
              requestedScopes: ["openid", "profile", "email"]
          rbac:
            policy.csv: |
              g, argocd:admin, role:admin
        server:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            enabled: true
            hostname: argocd.internal.k8s.vogelherdweg.de
            extraHosts:
              - name: argocd.rock.k8s.vogelherdweg.de
            tls: true
            extraTls: 
              - hosts: 
                - argocd.internal.k8s.vogelherdweg.de
                - argocd.rock.k8s.vogelherdweg.de
                secretName: argocd-rock-k8s-vogelherdweg-de-tls
  - repoURL: git@github.com:MyChaOS87/sloth.git
    targetRevision: main
    path: argocd-base/argocd-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  project: argocd-base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

